version: '3'
services:
  redis-cache:
    build:
      context: .
      dockerfile: Dockerfile_redis
    image: rate-limiter-service-redis:latest
    env_file:
      - .env
    expose:
      - "${SPRING_DATA_REDIS_PORT:-6379}"
    ports:
      - "${SPRING_DATA_REDIS_PORT:-6379}:${SPRING_DATA_REDIS_PORT:-6379}"
    networks:
      - app-network
    restart: unless-stopped
    volumes:
      # Other services access the Redis dump.rdb file from this directory
      - "redis-cache:${APP_REDIS_DATA_DIR:-/data}"

  ratelimiter-service:
    build:
      context: .
      dockerfile: Dockerfile
    image: rate-limiter-service:latest
    env_file:
      - .env
    expose:
      - "${SERVER_PORT:-8080}"
    ports:
      - "${SERVER_PORT:-8080}:${SERVER_PORT:-8080}"
    networks:
      - app-network
    restart: unless-stopped
    volumes:
      # We back up the Redis dump.rdb file from this directory
      - "redis-cache:${APP_REDIS_DATA_DIR:-/data}"
    depends_on:
      - redis-cache
    environment:
      SERVER_PORT: "${SERVER_PORT:-8080}"
      SPRING_CACHE_TYPE: "redis"
      SPRING_CACHE_REDIS_CACHE_NULL_VALUES: "${SPRING_CACHE_REDIS_CACHE_NULL_VALUES:-false}"
      SPRING_DATA_REDIS_HOST: "${SPRING_DATA_REDIS_HOST:-redis-cache}"
      SPRING_DATA_REDIS_PORT: "${SPRING_DATA_REDIS_PORT:-6379}"
      SPRING_DATA_REDIS_DATABASE: "${SPRING_DATA_REDIS_DATABASE:-0}"
      SPRING_DATA_REDIS_TIMEOUT: "${SPRING_DATA_REDIS_TIMEOUT:-60000}"
#      logging.level.org.springframework.web.filter.CommonsRequestLoggingFilter: "debug"
#      logging.level.io.github.poshjosh.ratelimiter.raas.persistence: "debug"
#      logging.level.org.springframework: "debug"
#      logging.level.io.github.poshjosh: "debug"

networks:
  app-network:
    driver: bridge

volumes:
  redis-cache: