FROM redis:7.0-alpine

LABEL io.github.poshosh.image.authors="https://github.com/poshjosh"
#
#RUN addgroup -S spring && adduser -S spring -G spring
#USER spring:spring

ARG TIMEZONE=UTC

# We do this so all containers can share the same timezone,
# We need tzdata because alpine linux does not come with it, by default.
RUN apk add --no-cache tzdata \
    && ln -snf /usr/share/zoneinfo/"$TIMEZONE" /etc/localtime && echo "$TIMEZONE" > /etc/timezone

# --save 20 1 instructs the redis server to save the dataset to disk every 20 seconds,
# if there are one or more writes
CMD exec redis-server --port ${SPRING_DATA_REDIS_PORT:-6379} \
    --save ${APP_REDIS_BACKUP_INTERVAL:-20} 1 --loglevel ${REDIS_LOGLEVEL:-notice}