management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include:
          - health
          - info
server:
  port: 8080
spring:
  application:
    name: rate-limiter-service
  cloud:
    aws:
      credentials:
        access-key: ${SPRING_CLOUD_AWS_CREDENTIALS_ACCESS_KEY}
        secret-key: ${SPRING_CLOUD_AWS_CREDENTIALS_SECRET_KEY}
      s3:
        region: us-east-2
app:
  aws:
    s3:
      bucket-name: raas-bucket
  redis:
    data-dir: /data
    backup-interval: 20

# TODO - Logging didn't show up when we put these in application.dev.yml and run in 'dev' profile.
logging:
  level:
    ROOT: info
    #web: debug
    io.github.poshjosh: info
#    io.github.poshjosh.ratelimiter.raas.resources: trace
#    io.github.poshjosh.ratelimiter.raas.services: trace
#    io.github.poshjosh.ratelimiter.matcher.DefaultMatchContext: trace
#    io.github.poshjosh.ratelimiter.matcher.MatchVisitors: trace
    org.springframework: info
    #org.springframework.web.filter.CommonsRequestLoggingFilter: debug
    #    org.springframework.cache: info
    #    org.springframework.data.redis: info
    #    org.springframework.data.redis.core: info
    #    org.springframework.data.redis.connection: info
